name: run test v0 
on:
  push:
    paths:
      - 'tests/test_v0.sh'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.8]
    steps: 
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          npm install -g bats
          sudo apt update && sudo apt install jellyfish
          pip3 install pandas
          jellyfish --version
      - name: Run tests
        run: bash tests/test_v0.sh