name: run v0 with bash
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.8]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      -name: Install dependencies
        run: sudo apt update && sudo apt install jellyfish
        run: pip install pandas
        run: jellyfish --version
      -name: Run naive pipeline
        run: bash v0/test_v0.sh